---
title: ""
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Programación Acturial 3
## Caso 3 (CodeBook)
### Cocoletzi Conde Anayeli
### Campos Campos Emmanuel
### Contreras castillo Eduardo
### Delgadillo Lopéz Erik
### Romero Gregorio Rodrigo





#### Despcipción de la base de datos

Los experimentos se han llevado a cabo con un grupo de 30 voluntarios dentro de un grupo de edad de 19-48 años. Cada persona lleva a cabo seis actividades (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) usando un teléfono inteligente (Samsung Galaxy S II) en la cintura.

A través de su acelerómetro incorporado y giroscopio, hemos capturado aceleración lineal 3-axial y velocidad angular 3-axial a una velocidad constante de 50 Hz. Los experimentos han sido grabadas en vídeo para etiquetar los datos de forma manual. El conjunto de datos obtenidos se ha dividido aleatoriamente en dos grupos, en los que se seleccionó el 70% de los voluntarios para la generación de los datos de entrenamiento y 30% de los datos de prueba.
Las señales del sensor (acelerómetro y giroscopio) fueron pre-procesados mediante la aplicación de filtros de ruido y luego se muestrean en deslizamiento de ancho fijo ventanas de 2,56 seg y 50% de solapamiento (128 lecturas / ventana). La señal de aceleración del sensor, que tiene componentes gravitacionales y el movimiento del cuerpo, se separó usando un filtro de paso bajo Butterworth en aceleración cuerpo y la gravedad. La fuerza de la gravedad se supone que tiene sólo componentes de baja frecuencia, por lo tanto, se utilizó un filtro con 0,3 Hz frecuencia de corte. A partir de cada ventana, un vector de características se obtuvo mediante el cálculo de las variables de tiempo y el dominio de la frecuencia.


####Leemos los archivos y unimos
```

    subject_test <- read.table("./test/subject_test.txt", col.names=c("Subject"))
    subject_train <- read.table("./train/subject_train.txt", col.names=c("Subject"))
    features_test <- read.table("./test/X_test.txt")
    features_train <- read.table("./train/X_train.txt")
    features_test <- read.table("./test/X_test.txt")
    features_train <- read.table("./train/X_train.txt")
    activities_test <- read.table("./test/Y_test.txt")
    activities_train <- read.table("./train/Y_train.txt")
    feature_list <- read.table("features.txt", col.names=c("index", "feature_labels"))
    activity_labels<-read.table("activity_labels.txt",sep="               ",col.names=c("activityLabel","Activity"))
    

```
####Combinamos los datos de Test con los de Train
```
    subject_all <- rbind(subject_train, subject_test)
    
    features_data <- rbind(features_test, features_train)
    
    activities_all <- rbind(activities_test, activities_train)
    colnames(activities_all) <- "activityLabel"
    activities_all<-join(activities_all,activity_labels,by="activityLabel",type="left")
    
```
####Extraemos Los que datos que tienen las palabras mean y , para ello creamos el vector que contenga cada uno de los nombres de la antividad, entonces extramos los datos de la columna feature_labels
```
    feature_labels <- feature_list$feature_labels
    
    features_subset <- grepl('mean\\(\\)|std\\(\\)',feature_labels)
    head(features_subset,2)
    
```
    
####Colocamos etiquetas
```
    colnames(features_data) <- feature_labels
    
``` 
    
####Creamos el vector que contiene cada uno de los nombres que tienen mean o std, para luego extraerlos.
```
    feature_list <- as.character(feature_labels[features_subset])
    features_data <- features_data[,features_subset]
    
```    
    
####Combinamos cada tabla para tener una sola
```
    all_df <- cbind(features_data, activities_all, subject_all)
    
```
    
####Une las data remoldelados mejorados (ponerlos entendibles)
```
    tdf <- melt(all_df, id=c("Subject", "Activity"), measure.vars=feature_list)
    tdf <- dcast(tdf, Activity + Subject ~ variable, mean)
    tdf <- tdf[order(tdf$Subject, tdf$Activity),]
    rr <- nrow(tdf)
    rownames(tdf) <- 1:rr
    tdf <- tdf[,c(2,1,3:68)]

```    

####Creamos la nueva base 
```
    write.table(tdf,file="New_database.txt") 
    
```


